# for development environment on local PC

cloud:
  aws:
    # AWS common
    region:
      static: ap-northeast-1
      auto: false
    credentials:
      instanceProfile: false
    # SES
    ses:
      region: us-east-1
    # SQS
    sqs:
      region: ap-northeast-1
    # CloudWatch
    cloudwatch:
      region: ${cloud.aws.region.static}

# RDB(ローカルPC上のPostgreSQLを使用)
database:
  url: jdbc:postgresql://localhost:5432/atrs?socketTimeout=120&connectTimeout=120
  username: postgres
  password: postgres
  driverClassName: org.postgresql.Driver

# connection pool for RDB
# bean定義に反映させる必要があることに注意
cp:
  maxActive: 96
  maxIdle: 16
  minIdle: 16
  initialSize: 16
  maxWait: 60000
  validationQuery: SELECT 1
  testOnConnect: true
  testWhileIdle: true
  # Amazon failover の最大値
  # 参考 [http://docs.aws.amazon.com/ja_jp/AmazonRDS/latest/UserGuide/Concepts.MultiAZ.html]
  timeBetweenEvictionRunsMillis: 120000
  removeAbandoned: true
  removeAbandonedTimeout: 60

# configurations for notification
reservation:
  notification:
    queue: RESERVATION_NOTICE
    concurrency: 5-10
    mail:
      from: terasoluna-cloud@kits.nttdata.co.jp
      templateFile: reservation-mail.ftl

# Logging
logging:
  path: /var/log/atrslogs
  # Workaround for duplicated log files
  config: classpath:atrsback-logback-spring.xml

# avoid a confliction of JMX endpoint on local environment
endpoints:
  jmx:
    unique-names: true
