# for performance test environment on EC2

cloud:
  aws:
    # AWS common
    region:
      auto: true
    # SES
    ses:
      region: us-east-1
    # SQS
    sqs:
      region: ap-northeast-1
    # CloudWatch
    cloudwatch:
      region: ap-northeast-1

# RDB(RDSを使用)
database:
  url: jdbc:postgresql://cn-performance-db1.XXXX.ap-northeast-1.rds.amazonaws.com:5432/atrs?socketTimeout=120&connectTimeout=120
  username: postgres
  password: postgres
  driverClassName: org.postgresql.Driver

# connection pool for RDB
# bean定義に反映させる必要があることに注意
cp:
  maxActive: 62
  maxIdle: 62
  minIdle: 62
  initialSize: 62
  maxWait: 5000
  validationQuery: SELECT 1
  testOnConnect: true
  testWhileIdle: true
  # Amazon failover の最大値
  # 参考 [http://docs.aws.amazon.com/ja_jp/AmazonRDS/latest/UserGuide/Concepts.MultiAZ.html]
  timeBetweenEvictionRunsMillis: 120000
  removeAbandoned: true
  removeAbandonedTimeout: 60

# configurations for notification
reservation:
  notification:
    # 環境毎にキューを切り替える。
    queue: cn-performance-queue
    concurrency: 5-10
    mail:
      from: xx@xx.xx.xx.xx
      templateFile: reservation-mail.ftl

# Logging
logging:
  path: /var/log/atrslogs
  # Workaround for duplicated log files
  config: classpath:atrsback-logback-spring.xml
  level:
    root: warn
